version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: cookie
      POSTGRES_USER: rani
      POSTGRES_DB: pf
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db: {}